version: '3.7'

services:
    web:
        build: 
          context: ./
          dockerfile: Dockerfile
        command: >
          bash -c "
            pip install config 
            pip install eventlet 
            pip install gunicorn 
            python manage.py collectstatic --noinput
            python manage.py migrate
            gunicorn -w 3 --bind 0.0.0.0:8000 djdocker.wsgi:application --env DJANGO_SETTINGS_MODULE=djdocker.settings
          "
        volumes:
        - .:/web_django
        ports:
        - '8000:8000'
          
